// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Return all pets in the store
	// (GET /pet)
	GetPets(ctx echo.Context) error
	// Add a new pet to the store
	// (POST /pet)
	AddPet(ctx echo.Context) error
	// Deletes a pet
	// (DELETE /pet/{petId})
	DeletePet(ctx echo.Context, petId int64) error
	// Find pet by ID
	// (GET /pet/{petId})
	GetPetById(ctx echo.Context, petId int64) error
	// Updates a pet in the store with form data
	// (PUT /pet/{petId})
	UpdatePetById(ctx echo.Context, petId int64) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetPets converts echo context to params.
func (w *ServerInterfaceWrapper) GetPets(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPets(ctx)
	return err
}

// AddPet converts echo context to params.
func (w *ServerInterfaceWrapper) AddPet(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.AddPet(ctx)
	return err
}

// DeletePet converts echo context to params.
func (w *ServerInterfaceWrapper) DeletePet(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "petId" -------------
	var petId int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "petId", runtime.ParamLocationPath, ctx.Param("petId"), &petId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter petId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.DeletePet(ctx, petId)
	return err
}

// GetPetById converts echo context to params.
func (w *ServerInterfaceWrapper) GetPetById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "petId" -------------
	var petId int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "petId", runtime.ParamLocationPath, ctx.Param("petId"), &petId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter petId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetPetById(ctx, petId)
	return err
}

// UpdatePetById converts echo context to params.
func (w *ServerInterfaceWrapper) UpdatePetById(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "petId" -------------
	var petId int64

	err = runtime.BindStyledParameterWithLocation("simple", false, "petId", runtime.ParamLocationPath, ctx.Param("petId"), &petId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter petId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.UpdatePetById(ctx, petId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/pet", wrapper.GetPets)
	router.POST(baseURL+"/pet", wrapper.AddPet)
	router.DELETE(baseURL+"/pet/:petId", wrapper.DeletePet)
	router.GET(baseURL+"/pet/:petId", wrapper.GetPetById)
	router.PUT(baseURL+"/pet/:petId", wrapper.UpdatePetById)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RWTY/bNhD9K8S0R1lyNkUPum2628JA0Rppcgp8oMWxxJQiueTIrrHQfy+GlPfDcrMI",
	"kDYocllrKXL45r03M7qHxvXeWbQUob6H2HTYy/R4G4IL/OCD8xhIY1punEL+3bnQS4IatKUff4AC6Ogx",
	"/4stBhgL6DFG2abd08tIQdsWxrGAgHeDDqig/vCwscjRNw/B3PYjNsSx1kgcRxrz+w7qD/fwfcAd1PBd",
	"9ZhANaGv1khv8W7AyEfPE9CK/yqMTdCetLNQw3ur7wYUWgm3E9Sh8EhQvJzjWR5awWbcZLQnADMCrewv",
	"UVJAJElDnIPzSCK/E9omdJFcYLbQDj3fK/dSG7k1vObRKg5YQHRGPeHyH7hPcDYjL2u7c/Pr33U6Ch2F",
	"FFH33qBYIyUAImLYYyjFuw5FL7UVWS69x0xjPkdODBFFE1ASCikOLvypbSucRyu9Fq9FCtujJclXcpKt",
	"MzLlYHSDNuIjb3DtZdOhuCqXUMAQDNTQEfm6qg6HQynT29KFtpqOxurX1U+3v/1xu7gql2VHvWGuSZPh",
	"aKdcoIA9hpgzflUuyyXvmiBCDa/LZfmK2ZXUJYkqnw3Z5h8WOKFfKajhFyQODMx09I5R8Kar5TJXkCW0",
	"2c7eG92kg9XHyJefSjA5lbBPB1/wekooiyxDkEdIaj5XMQ5NgzHuBiMesELatZODoc/C9Sk4uWtcAIDT",
	"iwLi0PcyHKGGt0hDsEIawwU3szfJNrJFmWquKu/iBbKvlVqnag254t44dfxi6TztJPOc1kiT5wV1koRF",
	"VMnwWxRSKVT8/DSjx8KjMOA488erLwn8f2ODa6WEFBYP7IJzyp6ZoIC/FjwiWrSLSe7F1qnjYmoO/JyC",
	"c3lW9x5ppcbc0gwSzs1zk9azf7wMskfCENOAmUutk55TKG6X3JwldVCcmlO6cKZz8YS0l0fKZuaKq3lT",
	"ZjgZiPrq8mUOeUDkqXletlOLfB4ol36eKrY1p4l7qY++OSZOPynP6oZHzmSfkGL/lwotv8m6/VlblTjf",
	"HsXq5lLDHi706/deyVRyn6nreYMdUhz1L8v8NUeKm3I8n4svTZFv043ZV1MbekaZOGjqBAsulCQ5MyrH",
	"mVbO/Xe7x3Ckjr9X5dYNJI5uCGL6uHv0Goyb8e8AAAD//6ltv3NLDQAA",
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file.
func GetSwagger() (*openapi3.Swagger, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	swagger, err := openapi3.NewSwaggerLoader().LoadSwaggerFromData(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("error loading Swagger: %s", err)
	}
	return swagger, nil
}
